apache: Modernize ducktape
sbitio/puppet-ducktape pull request #61
Opened 2022-01-10 13:03 UTC by KrisMagjistari

2022-01-14 09:01 UTC, jonhattan requested changes

2022-01-14 09:01 UTC, jonhattan commented on manifests/apache/shield_vhost.pp
>    $docroot         = $::apache::docroot,
El tipo aquí sería `Stdlib::Absolutepath`

2022-01-14 09:01 UTC, jonhattan commented on manifests/apache/shield_vhost.pp
>    $custom_fragment = undef,
tipo string

2022-01-14 09:01 UTC, jonhattan commented on manifests/apache.pp
> +  Hash $defaults = {},
Falta añadir las reglas de lookup en `modules/ducktape/data/common.yaml` para los 2 hashes.

2022-01-18 09:09 UTC, jonhattan commented on manifests/apache.pp
> +  Hash $defaults = {},
test

2022-01-18 09:10 UTC, KrisMagjistari reviewed
Datatypes problems

2022-01-18 09:29 UTC, jonhattan commented on manifests/apache/external/monit.pp
>    $extra_tests    = [],
* conn_tolerance, extra_alerts: el valor por defecto te da la pista
* alerts, sigue la pista... hasta https://github.com/sbitio/puppet-monit/blob/master/manifests/check/service.pp#L84 ... pon también el mismo default que en monit

2022-01-18 09:32 UTC, jonhattan commented on manifests/apache/conf.pp
>    $content    = undef,
Si sigues la pista puedes intuir que $content es string.

Para los undef se pone Optional[], por lo tanto: `Optional[String] $content = undef`

2022-01-18 10:08 UTC, jonhattan commented on data/common.yaml
> +      knockout_prefix: --
Tienes un ejemplo completo en `glue::php`. Revisa estos ficheros:

* modules-custom/glue/data/common.yaml
* modules-custom/glue/manifests/php.pp

2022-01-18 13:07 UTC, KrisMagjistari commented on manifests/apache/conf.pp
>    $content    = undef,
Hecho

2022-01-18 13:07 UTC, KrisMagjistari commented on manifests/apache/external/monit.pp
>    $extra_tests    = [],
Hecho

2022-01-21 16:43 UTC, jonhattan approved these changes

2022-01-21 16:43 UTC, merged