apt: modernize ducktape
sbitio/puppet-ducktape pull request #63
Opened 2022-01-10 13:15 UTC by KrisMagjistari

2022-01-14 09:04 UTC, jonhattan requested changes

2022-01-14 09:04 UTC, jonhattan commented on manifests/apt.pp
> +  Hash $source_defaults = {},
Falta añadir las reglas de lookup en `modules/ducktape/data/common.yaml`

2022-01-14 09:04 UTC, jonhattan commented on manifests/apt.pp
>    validate_bool($enabled)
Quitar todos los validate de todos los MR

2022-01-14 09:04 UTC, jonhattan commented on manifests/apt/autoload.pp
> +  Boolean $source = true,
Ambos en plural

2022-01-17 17:30 UTC, KrisMagjistari commented on manifests/apt.pp
>    validate_bool($enabled)
Hecho

2022-01-17 17:30 UTC, KrisMagjistari commented on manifests/apt.pp
> +  Hash $source_defaults = {},
Añadidas reglas de lookup para keys y sources

2022-01-17 17:31 UTC, KrisMagjistari commented on manifests/apt/autoload.pp
> +  Boolean $source = true,
Hecho

2022-01-17 17:34 UTC, KrisMagjistari commented
Se ha creado un MR en core para reflejar el cambio de nombres de los hashes: https://gitlab.sbit.io/sbitio/core/-/merge_requests/424

2022-01-18 11:51 UTC, merged