inifile: modernize ducktape
sbitio/puppet-ducktape pull request #64
Opened 2022-01-10 14:19 UTC by KrisMagjistari

2022-01-14 09:05 UTC, jonhattan requested changes

2022-01-14 09:05 UTC, jonhattan commented on manifests/inifile.pp
> +  Hash $defaults = {},
Falta añadir las reglas de lookup en `modules/ducktape/data/common.yaml`

2022-01-17 17:37 UTC, KrisMagjistari commented on manifests/inifile.pp
> +  Hash $defaults = {},
Reglas creadas para el hash settings.

2022-01-21 16:14 UTC, jonhattan approved these changes

2022-01-21 16:14 UTC, merged