gluster-module: modernize ducktape
sbitio/puppet-ducktape pull request #65
Opened 2022-01-10 14:22 UTC by KrisMagjistari

2022-01-14 09:05 UTC, jonhattan requested changes

2022-01-14 09:05 UTC, jonhattan commented on manifests/gluster.pp
> +  Hash $mounts = {},
Falta añadir las reglas de lookup en `modules/ducktape/data/common.yaml`

2022-01-18 09:25 UTC, KrisMagjistari commented on manifests/gluster.pp
> +  Hash $mounts = {},
hecho

2022-01-21 16:40 UTC, jonhattan approved these changes

2022-01-21 16:40 UTC, merged