letsencrypt: modernize-ducktape
sbitio/puppet-ducktape pull request #69
Opened 2022-01-10 14:51 UTC by KrisMagjistari

2022-01-14 09:10 UTC, jonhattan requested changes

2022-01-14 09:10 UTC, jonhattan commented on manifests/letsencrypt.pp
> +  Hash $certonlys = {},
Falta añadir las reglas de lookup en `modules/ducktape/data/common.yaml`

2022-01-18 11:42 UTC, KrisMagjistari commented
MR core: https://gitlab.sbit.io/sbitio/core/-/merge_requests/428

2022-01-21 16:26 UTC, jonhattan approved these changes

2022-01-21 16:26 UTC, merged