openvpn: modernize ducktape
sbitio/puppet-ducktape pull request #74
Opened 2022-01-11 13:02 UTC by KrisMagjistari

2022-01-14 09:12 UTC, jonhattan requested changes

2022-01-18 11:55 UTC, KrisMagjistari commented on manifests/openvpn.pp
> +  Hash $revokes = {},
Hecho

2022-01-18 11:55 UTC, KrisMagjistari commented
MR core: https://gitlab.sbit.io/sbitio/core/-/merge_requests/430

2022-01-21 16:23 UTC, jonhattan approved these changes

2022-01-21 16:24 UTC, merged