systemd: modernize ducktape
sbitio/puppet-ducktape pull request #78
Opened 2022-01-11 13:15 UTC by KrisMagjistari

2022-01-14 09:18 UTC, jonhattan requested changes

2022-01-14 09:18 UTC, jonhattan commented on manifests/systemd.pp
> +  Hash $networks = {},
Falta añadir las reglas de lookup en `modules/ducktape/data/common.yaml`

2022-01-18 12:22 UTC, KrisMagjistari commented on manifests/systemd.pp
> +  Hash $networks = {},
Hecho

2022-01-18 12:23 UTC, KrisMagjistari commented
MR core: https://gitlab.sbit.io/sbitio/core/-/merge_requests/431

2022-01-21 16:20 UTC, jonhattan approved these changes

2022-01-21 16:20 UTC, merged