vcsrepo: modernize ducktape
sbitio/puppet-ducktape pull request #79
Opened 2022-01-11 13:18 UTC by KrisMagjistari

2022-01-14 09:18 UTC, jonhattan requested changes

2022-01-14 09:18 UTC, jonhattan commented on manifests/vcsrepo.pp
> +  Boolean $enabled = true,
Falta poner los parámetros 

Falta añadir las reglas de lookup en `modules/ducktape/data/common.yaml`

2022-01-18 12:31 UTC, KrisMagjistari commented on manifests/vcsrepo.pp
> +  Boolean $enabled = true,
Hecho

2022-01-21 16:10 UTC, jonhattan approved these changes

2022-01-21 16:10 UTC, merged